# Supabase local development config
[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15
extension_schemas = ["extensions"]
seed_file_path = "seed.sql"

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
smtp_port = 54324
pop3_port = 54325
web_port = 54326

[storage]
file_size_limit = 52428800

[auth]
external_oauth_debug = false
